const glassPanel =
  "linear-gradient(180deg, rgba(255,250,245,0.78) 0%, rgba(255,243,234,0.72) 100%)";

const solidPanel =
  "linear-gradient(180deg, rgba(255,250,245,0.96) 0%, rgba(255,242,233,0.96) 100%)";

const chartSurface =
  "linear-gradient(180deg, rgba(255,247,240,0.98) 0%, rgba(252,238,225,0.98) 100%)";

const components = {
  themeSelector: {
    wrapper: {
      display: "grid",
      gap: 6,
      maxWidth: 240,
    },
    label: {
      fontSize: 12,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: "0.14em",
      color: "#7b6558",
    },
    select: {
      width: "100%",
      appearance: "none",
      WebkitAppearance: "none",
      MozAppearance: "none",
      background: solidPanel,
      color: "#201714",
      border: "1px solid rgba(91,62,46,0.12)",
      borderRadius: 16,
      padding: "12px 42px 12px 14px",
      fontSize: 15,
      fontWeight: 600,
      boxShadow: "0 4px 12px rgba(72,44,29,0.06)",
      outline: "none",
      cursor: "pointer",
    },
    caret: {
      position: "absolute",
      top: "50%",
      right: 14,
      transform: "translateY(-50%)",
      pointerEvents: "none",
      color: "#7b6558",
      fontSize: 12,
    },
  },

  summaryCard: {
    card: {
      position: "relative",
      overflow: "hidden",
      background: solidPanel,
      border: "1px solid rgba(91,62,46,0.12)",
      borderRadius: 16,
      boxShadow: "0 6px 16px rgba(72,44,29,0.08)",
      padding: 10,
      display: "grid",
      gap: 4,
      minHeight: 66,
    },
    accentBar: {
      position: "absolute",
      top: 0,
      left: 0,
      width: 3,
      height: "100%",
    },
    glowOverlay: {
      position: "absolute",
      inset: 0,
      pointerEvents: "none",
    },
    label: {
      position: "relative",
      zIndex: 1,
      fontSize: 11,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: "0.12em",
      color: "#7b6558",
      paddingLeft: 8,
    },
    value: {
      position: "relative",
      zIndex: 1,
      fontSize: 20,
      lineHeight: 1.05,
      fontWeight: 800,
      color: "#201714",
      paddingLeft: 8,
      wordBreak: "break-word",
    },
  },

  chartCard: {
    card: {
      background: glassPanel,
      border: "1px solid rgba(91,62,46,0.12)",
      borderRadius: 16,
      boxShadow: "0 6px 16px rgba(72,44,29,0.08)",
      padding: 20,
      display: "grid",
      gap: 8,
    },
    title: {
      margin: 0,
      fontSize: 11,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: "0.14em",
      color: "#6f594d",
    },
    inner: {
      background: chartSurface,
      border: "1px solid rgba(91,62,46,0.10)",
      borderRadius: 14,
      padding: 8,
      boxShadow: "inset 0 1px 0 rgba(255,255,255,0.55)",
      minHeight: 0,
    },
  },

  uploadPanel: {
    section: {
      background: glassPanel,
      border: "1px solid rgba(91,62,46,0.12)",
      borderRadius: 16,
      boxShadow: "0 6px 16px rgba(72,44,29,0.08)",
      padding: 12,
      display: "grid",
      gap: 8,
    },
    topRow: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "start",
      gap: 8,
      flexWrap: "wrap",
    },
    title: {
      margin: 0,
      fontSize: 12,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: "0.14em",
      color: "#6f594d",
    },
    body: {
      margin: "3px 0 0 0",
      fontSize: 12,
      lineHeight: 1.3,
      color: "#2c211d",
    },
    ghostButton: {
      border: "1px solid rgba(91,62,46,0.12)",
      background: "rgba(255,255,255,0.45)",
      color: "#2c211d",
      borderRadius: 999,
      padding: "6px 12px",
      cursor: "pointer",
      fontSize: 12,
    },
    primaryButton: {
      border: "1px solid #eb7d64",
      background: "#eb7d64",
      color: "#fffaf6",
      borderRadius: 12,
      padding: "8px 14px",
      cursor: "pointer",
      fontSize: 12,
      fontWeight: 700,
      boxShadow: "0 6px 14px rgba(235,125,100,0.18)",
    },
    optionChip: {
      display: "inline-flex",
      alignItems: "center",
      gap: 8,
      border: "1px solid rgba(91,62,46,0.12)",
      background: "rgba(255,255,255,0.45)",
      color: "#2c211d",
      borderRadius: 12,
      padding: "8px 12px",
      fontSize: 12,
      cursor: "pointer",
    },
    statsGrid: {
      display: "grid",
      gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
      gap: 8,
    },
    statCard: {
      background: solidPanel,
      border: "1px solid rgba(91,62,46,0.12)",
      borderRadius: 12,
      padding: 8,
    },
    statLabel: {
      fontSize: 10,
      textTransform: "uppercase",
      letterSpacing: "0.12em",
      color: "#7b6558",
      marginBottom: 3,
    },
    statValue: {
      fontSize: 18,
      fontWeight: 800,
      color: "#201714",
    },
    statBody: {
      fontSize: 11,
      lineHeight: 1.4,
      color: "#2c211d",
    },
    issueBox: {
      background: "rgba(217,92,79,0.08)",
      border: "1px solid rgba(217,92,79,0.22)",
      borderRadius: 12,
      padding: 10,
      display: "grid",
      gap: 6,
    },
    issueTitle: {
      fontSize: 11,
      textTransform: "uppercase",
      letterSpacing: "0.14em",
      color: "#b84c41",
    },
    issueList: {
      margin: 0,
      paddingLeft: 16,
      color: "#2c211d",
      fontSize: 12,
      lineHeight: 1.5,
    },
  },

  exportUploadPanel: {
    section: {
      background: glassPanel,
      border: "1px solid rgba(91,62,46,0.12)",
      borderRadius: 16,
      boxShadow: "0 6px 16px rgba(72,44,29,0.08)",
      padding: 12,
      display: "grid",
      gap: 8,
    },
    topRow: {
      display: "flex",
      justifyContent: "space-between",
      alignItems: "start",
      gap: 8,
      flexWrap: "wrap",
    },
    title: {
      margin: 0,
      fontSize: 12,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: "0.14em",
      color: "#6f594d",
    },
    body: {
      margin: "3px 0 0 0",
      fontSize: 12,
      lineHeight: 1.3,
      color: "#2c211d",
    },
    ghostButton: {
      border: "1px solid rgba(91,62,46,0.12)",
      background: "rgba(255,255,255,0.45)",
      color: "#2c211d",
      borderRadius: 999,
      padding: "6px 12px",
      cursor: "pointer",
      fontSize: 12,
    },
    primaryButton: {
      border: "1px solid rgba(44,33,29,0.18)",
      background: "rgba(255,255,255,0.52)",
      color: "#201714",
      borderRadius: 12,
      padding: "8px 14px",
      cursor: "pointer",
      fontSize: 12,
      fontWeight: 700,
      boxShadow: "0 6px 12px rgba(72,44,29,0.06)",
    },
    countCard: {
      background: solidPanel,
      border: "1px solid rgba(91,62,46,0.12)",
      borderRadius: 12,
      padding: 8,
    },
    countLabel: {
      fontSize: 10,
      textTransform: "uppercase",
      letterSpacing: "0.12em",
      color: "#7b6558",
      marginBottom: 3,
    },
    countValue: {
      fontSize: 18,
      fontWeight: 800,
      color: "#201714",
    },
  },

  tooltip: {
    container: {
      background: "rgba(255,250,245,0.98)",
      border: "1px solid rgba(91,62,46,0.12)",
      borderRadius: 16,
      boxShadow: "0 10px 24px rgba(72,44,29,0.08)",
      padding: 16,
      minWidth: 180,
    },
    label: {
      marginBottom: 10,
      fontSize: 12,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: "0.14em",
      color: "#7b6558",
    },
    row: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 16,
      fontSize: 13,
      color: "#2c211d",
    },
    keyWrap: {
      display: "flex",
      alignItems: "center",
      gap: 6,
      minWidth: 0,
    },
    dot: {
      width: 10,
      height: 10,
      borderRadius: 999,
      flex: "0 0 auto",
    },
    keyText: {
      color: "#7b6558",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    value: {
      fontWeight: 700,
      color: "#201714",
      flex: "0 0 auto",
    },
  },

  collapsibleSection: {
    wrapper: {
      display: "grid",
      gap: 14,
    },
    headerButton: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      width: "100%",
      background: "transparent",
      border: "none",
      padding: 0,
      cursor: "pointer",
      textAlign: "left",
    },
    title: {
      margin: 0,
      fontSize: 13,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: "0.14em",
      color: "#6f594d",
    },
    caret: {
      color: "#2c211d",
      fontSize: 12,
    },
    body: {
      display: "grid",
      gap: 16,
    },
  },

  dataTable: {
    wrapper: {
      background: glassPanel,
      border: "1px solid rgba(91,62,46,0.12)",
      borderRadius: 16,
      boxShadow: "0 6px 16px rgba(72,44,29,0.08)",
      padding: 12,
      display: "grid",
      gap: 8,
    },
    title: {
      margin: 0,
      fontSize: 11,
      fontWeight: 700,
      textTransform: "uppercase",
      letterSpacing: "0.14em",
      color: "#6f594d",
    },
    intro: {
      margin: 0,
      fontSize: 12,
      lineHeight: 1.4,
      color: "#2c211d",
    },
    tableWrap: {
      background: "rgba(255,250,245,0.72)",
      border: "1px solid rgba(91,62,46,0.10)",
      borderRadius: 12,
      padding: 8,
      overflowX: "auto",
    },
    table: {
      width: "100%",
      borderCollapse: "collapse",
      fontSize: 12,
      color: "#2c211d",
    },
    headCell: {
      padding: "6px 8px",
      textAlign: "left",
      fontWeight: 700,
      color: "#201714",
      whiteSpace: "nowrap",
    },
    bodyCell: {
      padding: "6px 8px",
      borderTop: "1px solid rgba(91,62,46,0.08)",
      whiteSpace: "nowrap",
    },
    rowAlt: {
      background: "rgba(91,62,46,0.03)",
    },
  },
};

export default components;